version: '3.8'

services:

  frontend:
    image: pradeepmd/codejudge-frontend
    ports:
      - "3000:3000"
    depends_on:
      - auth
      - problem
      - submission

  auth:
    image: pradeepmd/codejudge-auth-service
    ports:
      - "5001:5001"

  problem:
    image: pradeepmd/codejudge-problem-service
    ports:
      - "5002:5002"

  submission:
    image: pradeepmd/codejudge-submission-service
    ports:
      - "5003:5003"
