services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: ${DB_NAME:-codejudge}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  auth-service:
    image: ${DOCKERHUB_USERNAME}/codejudge-auth-service:latest
    restart: always
    ports:
      - "3001:3001"
    environment:
      PORT: 3001
      JWT_SECRET: ${JWT_SECRET}
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: ${DB_NAME:-codejudge}
      DB_USER: ${DB_USER:-postgres}
      DB_PASSWORD: ${DB_PASSWORD:-postgres}
    depends_on:
      postgres:
        condition: service_healthy

  problem-service:
    image: ${DOCKERHUB_USERNAME}/codejudge-problem-service:latest
    restart: always
    ports:
      - "3002:3002"
    environment:
      PORT: 3002
      JWT_SECRET: ${JWT_SECRET}
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: ${DB_NAME:-codejudge}
      DB_USER: ${DB_USER:-postgres}
      DB_PASSWORD: ${DB_PASSWORD:-postgres}
      TC_DIR: /app/testcases
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - testcases_data:/app/uploads
      - ./seed/testcases:/app/testcases

  submission-service:
    image: ${DOCKERHUB_USERNAME}/codejudge-submission-service:latest
    restart: always
    ports:
      - "3003:3003"
    environment:
      PORT: 3003
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: ${DB_NAME:-codejudge}
      DB_USER: ${DB_USER:-postgres}
      DB_PASSWORD: ${DB_PASSWORD:-postgres}
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - testcases_data:/app/uploads
      - ./seed/testcases:/app/testcases

  frontend:
    image: ${DOCKERHUB_USERNAME}/codejudge-frontend:latest
    restart: always
    ports:
      - "5173:5173"
    depends_on:
      - auth-service
      - problem-service
      - submission-service

volumes:
  postgres_data:
  testcases_data:
